name: WBW
options:
  bundleIdPrefix: th.ac.mfu
  deploymentTarget:
    iOS: "18.0"
  createIntermediateGroups: true
packages:
  MapLibre:
    url: https://github.com/maplibre/maplibre-gl-native-distribution
    from: 6.0.0
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    from: 11.0.0
targets:
  WBW:
    type: application
    platform: iOS
    sources:
      - WBW
    dependencies:
      - package: MapLibre
        product: MapLibre
      - package: Firebase
        product: FirebaseMessaging
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: th.ac.mfu.wbwSwift
        PRODUCT_NAME: WBW
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: WBW/Info.plist
        CODE_SIGN_ENTITLEMENTS: WBW/WBW.entitlements
        TARGETED_DEVICE_FAMILY: "1"
        SWIFT_VERSION: "5.0"
        IPHONEOS_DEPLOYMENT_TARGET: "18.0"
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: NJL4K64JX5
        ENABLE_USER_SCRIPT_SANDBOXING: YES
  WBWTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - WBWTests
    dependencies:
      - target: WBW
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: th.ac.mfu.wbwSwiftTests
        GENERATE_INFOPLIST_FILE: YES
        IPHONEOS_DEPLOYMENT_TARGET: "18.0"
        SWIFT_VERSION: "5.0"
schemes:
  WBW:
    build:
      targets:
        WBW: all
    test:
      targets:
        - WBWTests
    run:
      config: Debug
